version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bgf_pp_scheduler
    ports:
      - "8080:8443" # HTTP 요청 처리
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/metadb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '0000'
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db
    volumes:
      - ./bgf_pp_scheduler-0.0.1-SNAPSHOT.jar:/app/scheduler/bgf_pp_scheduler-0.0.1-SNAPSHOT.jar

  db:
    image: mysql:8.0
    container_name: bgf_pp_scheduler_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: metadb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: