server:
    port: 8443

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER}

    jpa:
        hibernate:
            ddl-auto: none
joytel:
    api:
        customerOrder: "https://api.joytelshop.com/customerApi/customerOrder"
        couponRedeem: "https://api.joytelshop.com/customerApi/coupon/redeem"
    customerInfo:
        customerCode: "10391"
        customerAuth: "54534AA34A"
    log:
        file: "/Users/whwan/Desktop/joytelLogfile/joytel_logfile.JSON"